# Generated by Django 3.2.15 on 2022-08-30 15:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(null=True, unique=True, verbose_name='Ссылка')),
                ('source', models.TextField(blank=True, choices=[('Yandex', 'Яндекс'), ('Ozon', 'Озон')], max_length=6, null=True, verbose_name='Сервис')),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('tags', models.ManyToManyField(related_name='news', to='news_service.Tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['title'],
            },
        ),
    ]
